version: "3.8"

services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000"      # Setup UI
      - "80:80"          # Web dashboard
    volumes:
      - adguard_config:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work

volumes:
  adguard_config:
  adguard_work:
