version: "3.8"

services:
  db:
    image: postgres:15
    container_name: nextcloud_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ubayd
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  app:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ubayd
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db

volumes:
  db_data:
  nextcloud_data:
